### PR TITLE
MCLOUD-6029: Implement New Relic Logs in Context

### PR DESCRIPTION
**Pull request by billygilbert**
## Description
Implements the New Relic monolog enricher to enable New Relic logs in context
https://docs.newrelic.com/docs/logs/enable-logs/configure-logs-context/configure-logs-context-apm-agents
### Fixed Issues (if relevant)
1. MCLOUD-6029

### Manual testing scenarios
1. Use an environment with New Relic APM 9.3 or later
2. Increase application logging
3. Review traces in New Relic to validate logs are appearing.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Review by NadiyaS — DISMISSED** [review]

**Review by oshmyheliuk — DISMISSED** [review]

**Comment by billygilbert** [comment]
Added a patch to backport the interface necessary to allow Magento 2.1 compatibility.  We will probably need to manually verify the failed test, though, as It requires testing against latest version of ECE-Tools + the patches after that is merged.

**Comment by mveeramneni** [comment]
QA Approved

**Comment by billygilbert** [comment]
Resolved the merge issues but retesting those looks like they are causing an issue...Will continue to resolve those conflicts.

**Comment by billygilbert** [comment]
Conflicts resolved, re-tested and worked as expected.

**Review by oshmyheliuk — APPROVED** [review]

**Review by NadiyaS — APPROVED** [review]

**Comment by billygilbert** [comment]
Failed 2.1 builds are due to incompatibility issues between Magento 2.1, Monolog 1.16, and NewRelic log enricher 1.0.  
Resolution required backporting an interface in Monolog that was introduced in 1.24.  PR for that is here: https://github.com/magento/magento-cloud-patches/pull/48

**Comment by mveeramneni** [comment]
QA Approved again after resolvig conflicts.

**Pull request merged**
